"""add trip preferences to itineraries table

Revision ID: 5bff0f3df38c
Revises: 87966a22d999
Create Date: 2025-09-04 22:28:59.827649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bff0f3df38c'
down_revision: Union[str, None] = '87966a22d999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('trip_theme', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('itineraries', sa.Column('budget', sa.String(), nullable=True))
    op.add_column('itineraries', sa.Column('pace', sa.String(), nullable=True))
    op.add_column('itineraries', sa.Column('travel_mode', sa.String(), nullable=True))
    op.add_column('itineraries', sa.Column('group_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itineraries', 'group_type')
    op.drop_column('itineraries', 'travel_mode')
    op.drop_column('itineraries', 'pace')
    op.drop_column('itineraries', 'budget')
    op.drop_column('itineraries', 'trip_theme')
    # ### end Alembic commands ###
